from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app  = Flask(__name__)  # Decorator!

app.config['SECRET_KEY'] = '829c714a59906af44da4289266ccafed'   # Random string generated by secret module
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'     # Creates database in current directory
bcrypt = Bcrypt(app)
db = SQLAlchemy(app)

login_manager = LoginManager(app)
login_manager.login_view = 'login'
login_manager.login_message_category = 'info'

from flasky import routes